### ISSUE TITLE
Trieste

### ISSUE THREAD

**Issue by benedekrozemberczki** [kiss-oliver/TriFi#1]
This paper proposes an efficient sub-quadratic algorithm for this:

https://arxiv.org/abs/1602.07424

This paper uses the algorithm:

https://www.kdd.org/kdd2017/papers/view/ego-splitting-framework-from-non-overlapping-to-overlapping-clusters

**Comment by kiss-oliver** [comment]
Thanks, but if I can see it correctly they propose an approximation in undirected networks. The empirical issue we face requires us to be able to identify the actual triangles each node is included in (i.e. we will have a node-level cross sectional data), and our network is directed. Also nodes are heterogeneous and we are interested in what types of triangles they usually form (e.g. are agents from the same sub-population more likely to form a triangle, etc.) thus we need the exact triangles themselves to analyze patterns more in-depth. This tool will hopefully be able to return the triangles themselves efficiently.
